version: "3.8"

services:
  client:
    image: httpd:2.4
    container_name: client
    volumes:
      - ./build/ /usr/local/apache2/htdocs/
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 5050:80